<a href="https://colab.research.google.com/github/tazeendev/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
temperature1=[23.3,45.3,20.5,34.5,48.5]
total=0
for temp in temperature1:
  total +=temp

average1=total/len(temperature1)
print(average1)

34.42


In [ ]:
temperature2=np.array([23.3,45.3,20.5,34.5,48.5])
average2=np.mean(temperature2)
print(average2)

34.42


In [ ]:
python_list=[1,2,3,4,5,6]
print(python_list)
numpy_array=np.array([1,2,3,4,5,6])
print(numpy_array)
defult_value=np.full((3,4),4)
print(defult_value)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [ ]:
# types of array
array_1d=np.array([1,2,3,4,5,6])
print(array_1d)
array_2d=np.array([[1,2,3,4,5],
                  [1,2,3,4,56]])
print(array_2d)
array_3d=np.array([[[1,2,3,4,5],
                  [6,7,8,9,2]],
                   [[2,5,6,7,8],[2,5,6,7,8]]])
print(array_3d)
zero_array=np.zeros((3,4))
print(zero_array)
one_array=np.ones((3,5))
print(one_array)
identity=np.eye(3)
print(identity)

[1 2 3 4 5 6]
[[ 1  2  3  4  5]
 [ 1  2  3  4 56]]
[[[1 2 3 4 5]
  [6 7 8 9 2]]

 [[2 5 6 7 8]
  [2 5 6 7 8]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
3# continuous values
continous_values=np.arange(1,20,2)
print(continous_values)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
print(array_1d.shape)
print(array_2d.shape)
print(array_3d.shape)

(6,)
(2, 5)
(2, 2, 5)


In [ ]:
print(array_1d.size)
print(array_2d.size)
print(array_3d.size)

6
10
20


In [ ]:
print(array_1d.ndim)
print(array_2d.ndim)
print(array_3d.ndim)

1
2
3


In [ ]:
print(array_1d.dtype)
print(array_2d.dtype)

int64
int64


In [ ]:
print(array_1d.astype(float))
print(array_2d.astype(str))

[1. 2. 3. 4. 5. 6.]
[['1' '2' '3' '4' '5']
 ['1' '2' '3' '4' '56']]


In [ ]:
arr=np.array([23,24,25,28])
print(arr+2)
print(arr-2)

[25 26 27 30]
[21 22 23 26]


In [ ]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))

550
55.0
28.722813232690143
825.0
10
100


In [ ]:
print(arr[2])
print(arr[-1])
print(arr[1:4])
print(arr[1:6 : 20])
print(arr[:4])

30
100
[20 30 40]
[20]
[10 20 30 40]


In [ ]:
print(arr[arr>40])
# fancy indexing
print(arr[[0,3,6]])

[ 50  60  70  80  90 100]
[10 40 70]


In [ ]:
reshaped_array=arr.reshape(2,5)
print(reshaped_array)
print(array_2d.ravel())
print(array_2d.flatten())

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
[ 1  2  3  4  5  1  2  3  4 56]
[ 1  2  3  4  5  1  2  3  4 56]


In [ ]:
num_array=np.array([1,2,3,4,5,6,7,8,9])
print(num_array)
inserted_array=np.insert(num_array, 1, 10, axis=None)
print(inserted_array)

[1 2 3 4 5 6 7 8 9]
[ 1 10  2  3  4  5  6  7  8  9]


In [ ]:
append_array=np.append(num_array,[12,14,16])
print(append_array)

[ 1  2  3  4  5  6  7  8  9 12 14 16]


In [ ]:
arr1=np.array([12,14,16,18,20])
arr2=np.array([22,24,26,28,30])
concatenate_array=np.concatenate((arr1,arr2),axis=0)
print(concatenate_array)

[12 14 16 18 20 22 24 26 28 30]


In [ ]:
delete_arr=np.array([
    [1,2,3],[4,2,3]
])
delete_array=np.delete(delete_arr,0,axis=0)
print(delete_array)

[[4 2 3]]


In [ ]:
stack_arr1=np.array([1,2,3])
stack_arr2=np.array([2,3,5])
vstack_array=np.vstack((stack_arr1,stack_arr2))
print(vstack_array)
print(vstack_array.ndim)
hstack_array=np.hstack((stack_arr1,stack_arr2))
print(hstack_array)

[[1 2 3]
 [2 3 5]]
2
[1 2 3 2 3 5]


In [ ]:
split_arr=np.array([221,223,225,226,228,220])
splitted_array=np.split(split_arr,3)
print(splitted_array)

[array([221, 223]), array([225, 226]), array([228, 220])]


In [ ]:
# boradcasting concepts
# if boradcasting is not used in python numpy manually use loop which are very slow for large data
prices=[100,200,300,400,500]
discount=10
final_prices=[]
for price in prices:
  after_discount=price-(price*discount/100)
  final_prices.append(after_discount)
print(final_prices)
# with broadcasting
price_array=np.array([100,200,300,400,500])
discount_array=10
final_price_array=price_array-(price_array*discount/100)
print(final_price_array)

[90.0, 180.0, 270.0, 360.0, 450.0]
[ 90. 180. 270. 360. 450.]


In [ ]:
# vectorization
#without using numpy vectorization concepts
list1=[1,2,3]
list2=[4,5,6]
add_list=list1+list2# not add but manually add in a list [1,2,3,4,5,6]
print(add_list)
result=[x+y for x,y in zip(list1,list2)]
print(result)
# with numpy vectorization
add_arr1=np.array([1,2,3,4,5])
add_arr2=np.array([6,7,8,9,10])
result=add_arr1+add_arr2
print(result)

[1, 2, 3, 4, 5, 6]
[5, 7, 9]
[ 7  9 11 13 15]
